[package]
name = "vinyldb"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
colored = "2.1.0"
derive_more = "0.99.17"
indexmap = "2.2.5"
log = "0.4.21"
pretty_assertions = "1.4.0"
rustyline = "13.0.0"
sled = "0.34.7"
sqlparser = "0.43.1"
